-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'MARKETPLACE_UNIVERSITY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'MARKETPLACE_UNIVERSITY_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'MARKETPLACE_UNIVERSITY_DELETED';
