import { PrismaClient, CourseCategory, DegreeLevel } from '@prisma/client';

// Sample College Marketplace catalog — enough spread across provinces,
// universities, categories, degree levels, and fee ranges to exercise every
// filter. A couple of courses/colleges carry the richer Course Detail Page
// content (curriculum, career outcomes, etc.) so that UI has real data to
// render; the rest are left minimal on purpose to prove those sections
// degrade gracefully when the data isn't set. Idempotent (upsert by
// slug/name) so it's safe to re-run.
export async function seedMarketplace(prisma: PrismaClient) {
  const universities = await Promise.all(
    [
      { name: 'Tribhuvan University', shortName: 'TU' },
      { name: 'Pokhara University', shortName: 'PU' },
      { name: 'Kathmandu University', shortName: 'KU' },
    ].map((u) =>
      prisma.university.upsert({
        where: { name: u.name },
        update: { shortName: u.shortName },
        create: u,
      }),
    ),
  );
  const [tu, pu, ku] = universities;

  const colleges = [
    {
      slug: 'kathmandu-college-of-management',
      name: 'Kathmandu College of Management',
      description:
        'A leading management college in Kathmandu offering BBA, BBM, and MBA programs affiliated with Pokhara University.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Gwarko, Lalitpur',
      universityId: pu.id,
      website: 'https://kcm.edu.np',
      contactEmail: 'info@kcm.edu.np',
      contactPhone: '+977-1-5970003',
      eligibility: '+2 or equivalent with minimum 45% aggregate',
      requiredDocs:
        'Citizenship, +2 transcript & character certificate, passport photos',
      accreditation: 'UGC Accredited',
      isFeatured: true,
      courses: [
        {
          slug: 'bba',
          name: 'Bachelor of Business Administration',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '4 Years',
          durationMonths: 48,
          seatsAvailable: 60,
          tuitionFee: 380000,
          admissionFee: 20000,
          totalFee: 400000,
          feeBreakdown: [
            { label: 'Admission Fee', amount: 20000 },
            { label: 'Semester Fee (avg./sem.)', amount: 42000 },
            { label: 'Examination Fee (avg./sem.)', amount: 3500 },
            { label: 'Library & Lab Charges', amount: 8000 },
          ],
          description:
            'A comprehensive undergraduate program building core management, leadership, and analytical skills across finance, marketing, HR, and operations.',
          learningOutcomes: [
            'Apply core business and management principles to real-world scenarios',
            'Analyze financial statements and make data-driven business decisions',
            'Design and evaluate marketing strategies for diverse markets',
            'Lead teams and manage organizational change effectively',
          ],
          careerOutcomes: [
            {
              title: 'Business Analyst',
              description:
                'Analyze processes and recommend operational improvements.',
              salaryRange: 'NPR 35,000 – 70,000 / month',
            },
            {
              title: 'Marketing Executive',
              description:
                'Plan and execute marketing campaigns and brand strategy.',
              salaryRange: 'NPR 30,000 – 60,000 / month',
            },
            {
              title: 'Financial Analyst',
              salaryRange: 'NPR 35,000 – 75,000 / month',
            },
            { title: 'HR Officer', salaryRange: 'NPR 28,000 – 55,000 / month' },
          ],
          curriculum: [
            {
              semester: 'Semester 1',
              subjects: [
                'English I',
                'Business Mathematics',
                'Financial Accounting I',
                'Principles of Management',
              ],
            },
            {
              semester: 'Semester 2',
              subjects: [
                'English II',
                'Business Statistics',
                'Financial Accounting II',
                'Microeconomics',
              ],
            },
            {
              semester: 'Semester 3',
              subjects: [
                'Business Communication',
                'Macroeconomics',
                'Organizational Behavior',
                'Cost & Management Accounting',
              ],
            },
            {
              semester: 'Semester 4',
              subjects: [
                'Marketing Management',
                'Business Law',
                'Human Resource Management',
                'Corporate Finance',
              ],
            },
          ],
          industryDemand:
            'Consistently strong demand across banking, FMCG, and the fast-growing services sector in Nepal, with increasing openings in fintech and e-commerce.',
          intake: 'Fall (August) & Spring (February)',
          credits: 126,
          medium: 'English',
          attendanceType: 'Full-time',
          isPopular: true,
        },
        {
          slug: 'mba',
          name: 'Master of Business Administration',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.MASTER,
          duration: '2 Years',
          durationMonths: 24,
          seatsAvailable: 40,
          tuitionFee: 450000,
          admissionFee: 25000,
          totalFee: 475000,
        },
      ],
    },
    {
      slug: 'pulchowk-engineering-college',
      name: 'Pulchowk Engineering College',
      description:
        'Premier engineering institute affiliated with Tribhuvan University, offering undergraduate and graduate engineering programs.',
      province: 'Bagmati',
      district: 'Lalitpur',
      municipality: 'Lalitpur Metropolitan City',
      address: 'Pulchowk, Lalitpur',
      universityId: tu.id,
      website: 'https://pcampus.edu.np',
      contactEmail: 'info@pcampus.edu.np',
      contactPhone: '+977-1-5521543',
      eligibility:
        '+2 Science with Physics, Chemistry, Math; entrance exam required',
      requiredDocs:
        'Citizenship, +2 transcript, entrance exam scorecard, passport photos',
      accreditation: 'IOE / TU Accredited',
      isFeatured: true,
      courses: [
        {
          slug: 'be-computer',
          name: 'Bachelor of Engineering in Computer Engineering',
          category: CourseCategory.ENGINEERING,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '4 Years',
          durationMonths: 48,
          seatsAvailable: 48,
          tuitionFee: 520000,
          admissionFee: 30000,
          totalFee: 550000,
          feeBreakdown: [
            { label: 'Admission Fee', amount: 30000 },
            { label: 'Semester Fee (avg./sem.)', amount: 58000 },
            { label: 'Examination Fee (avg./sem.)', amount: 5000 },
            { label: 'Lab & Workshop Charges', amount: 15000 },
          ],
          description:
            'A rigorous, project-driven engineering program covering software systems, computer architecture, networks, and emerging technologies like AI and cloud computing.',
          learningOutcomes: [
            'Design, implement, and evaluate complex software systems',
            'Apply mathematical and engineering principles to computing problems',
            'Work effectively in multidisciplinary engineering teams',
            'Understand professional, ethical, and societal responsibilities of an engineer',
          ],
          careerOutcomes: [
            {
              title: 'Software Engineer',
              description: 'Build and maintain production software systems.',
              salaryRange: 'NPR 45,000 – 100,000 / month',
            },
            {
              title: 'Data Analyst',
              salaryRange: 'NPR 40,000 – 85,000 / month',
            },
            {
              title: 'Systems / Network Engineer',
              salaryRange: 'NPR 38,000 – 80,000 / month',
            },
            {
              title: 'Project Manager (IT)',
              description: 'Plan and deliver software projects end-to-end.',
              salaryRange: 'NPR 55,000 – 120,000 / month',
            },
          ],
          curriculum: [
            {
              semester: 'Semester 1',
              subjects: [
                'Engineering Mathematics I',
                'Physics',
                'Basic Electrical Engineering',
                'Programming in C',
              ],
            },
            {
              semester: 'Semester 2',
              subjects: [
                'Engineering Mathematics II',
                'Digital Logic',
                'Object Oriented Programming',
                'Engineering Drawing',
              ],
            },
            {
              semester: 'Semester 3',
              subjects: [
                'Data Structures & Algorithms',
                'Discrete Structures',
                'Computer Organization & Architecture',
                'Instrumentation',
              ],
            },
            {
              semester: 'Semester 4',
              subjects: [
                'Database Management Systems',
                'Operating Systems',
                'Object Oriented Analysis & Design',
                'Microprocessors',
              ],
            },
            {
              semester: 'Semester 5',
              subjects: [
                'Computer Networks',
                'Software Engineering',
                'Theory of Computation',
                'Artificial Intelligence',
              ],
            },
          ],
          industryDemand:
            'Very high — Nepal’s IT/software export sector and global remote-work opportunities continue to outpace the supply of qualified computer engineers.',
          intake: 'Fall (August)',
          credits: 138,
          medium: 'English',
          attendanceType: 'Full-time',
          isFeatured: true,
          isPopular: true,
        },
        {
          slug: 'be-civil',
          name: 'Bachelor of Engineering in Civil Engineering',
          category: CourseCategory.ENGINEERING,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '4 Years',
          durationMonths: 48,
          seatsAvailable: 48,
          tuitionFee: 500000,
          admissionFee: 30000,
          totalFee: 530000,
        },
      ],
    },
    {
      slug: 'kathmandu-university-school-of-medicine',
      name: 'Kathmandu University School of Medical Sciences',
      description:
        'Constituent medical school of Kathmandu University offering MBBS and allied health sciences programs.',
      province: 'Bagmati',
      district: 'Dhulikhel',
      municipality: 'Dhulikhel Municipality',
      address: 'Dhulikhel, Kavre',
      universityId: ku.id,
      website: 'https://kusms.edu.np',
      contactEmail: 'info@kusms.edu.np',
      contactPhone: '+977-11-490497',
      eligibility: '+2 Science with Biology; MBBS entrance exam required',
      requiredDocs:
        'Citizenship, +2 transcript, entrance exam scorecard, medical fitness certificate',
      accreditation: 'Nepal Medical Council Accredited',
      courses: [
        {
          slug: 'mbbs',
          name: 'Bachelor of Medicine, Bachelor of Surgery (MBBS)',
          category: CourseCategory.MEDICINE_HEALTH_SCIENCE,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '5 Years',
          durationMonths: 60,
          seatsAvailable: 20,
          tuitionFee: 4200000,
          admissionFee: 100000,
          totalFee: 4300000,
        },
      ],
    },
    {
      slug: 'pokhara-college-of-information-technology',
      name: 'Pokhara College of Information Technology',
      description:
        'IT-focused college in Pokhara affiliated with Pokhara University, specializing in computer applications and information management.',
      province: 'Gandaki',
      district: 'Kaski',
      municipality: 'Pokhara Metropolitan City',
      address: 'Lakeside, Pokhara',
      universityId: pu.id,
      website: 'https://pocit.edu.np',
      contactEmail: 'info@pocit.edu.np',
      contactPhone: '+977-61-462233',
      eligibility: '+2 or equivalent with minimum 40% aggregate',
      requiredDocs:
        'Citizenship, +2 transcript & character certificate, passport photos',
      accreditation: 'UGC Accredited',
      courses: [
        {
          slug: 'bim',
          name: 'Bachelor of Information Management',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '4 Years',
          durationMonths: 48,
          seatsAvailable: 50,
          tuitionFee: 340000,
          admissionFee: 15000,
          totalFee: 355000,
          feeBreakdown: [
            { label: 'Admission Fee', amount: 15000 },
            { label: 'Semester Fee (avg./sem.)', amount: 38000 },
            { label: 'Examination Fee (avg./sem.)', amount: 3000 },
            { label: 'Lab Charges', amount: 6000 },
          ],
          description:
            'A management-information-systems focused program blending business fundamentals with programming, databases, and IT project management.',
          learningOutcomes: [
            'Develop and maintain business information systems',
            'Apply database design and management principles',
            'Analyze organizational IT needs and propose solutions',
            'Manage small-to-medium IT projects using standard frameworks',
          ],
          careerOutcomes: [
            {
              title: 'Software Developer',
              salaryRange: 'NPR 35,000 – 75,000 / month',
            },
            {
              title: 'Business Analyst',
              salaryRange: 'NPR 32,000 – 65,000 / month',
            },
            {
              title: 'IT Project Coordinator',
              salaryRange: 'NPR 35,000 – 70,000 / month',
            },
            {
              title: 'Database Administrator',
              salaryRange: 'NPR 38,000 – 78,000 / month',
            },
          ],
          curriculum: [
            {
              semester: 'Semester 1',
              subjects: [
                'English I',
                'Computer Fundamentals',
                'Financial Accounting I',
                'Society & Technology',
              ],
            },
            {
              semester: 'Semester 2',
              subjects: [
                'English II',
                'C Programming',
                'Financial Accounting II',
                'Microeconomics',
              ],
            },
            {
              semester: 'Semester 3',
              subjects: [
                'Data Structures & Algorithms',
                'Database Management Systems',
                'Business Statistics',
                'Web Technology',
              ],
            },
            {
              semester: 'Semester 4',
              subjects: [
                'Object Oriented Programming',
                'Systems Analysis & Design',
                'Operating Systems',
                'Organizational Behavior',
              ],
            },
          ],
          industryDemand:
            'Steady demand from Nepal’s growing IT services and BPO sector for professionals who bridge business needs and technical implementation.',
          intake: 'Fall (August) & Spring (February)',
          credits: 126,
          medium: 'English',
          attendanceType: 'Full-time',
          isPopular: true,
        },
        {
          slug: 'bca',
          name: 'Bachelor of Computer Applications',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '4 Years',
          durationMonths: 48,
          seatsAvailable: 50,
          tuitionFee: 320000,
          admissionFee: 15000,
          totalFee: 335000,
          isPopular: true,
        },
        {
          slug: 'diploma-web-dev',
          name: 'Diploma in Web Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.DIPLOMA,
          duration: '1 Year',
          durationMonths: 12,
          seatsAvailable: 30,
          tuitionFee: 90000,
          admissionFee: 5000,
          totalFee: 95000,
        },
      ],
    },
    {
      slug: 'butwal-multiple-campus',
      name: 'Butwal Multiple Campus',
      description:
        'Public constituent campus in Butwal affiliated with Tribhuvan University, offering humanities, science, and education programs.',
      province: 'Lumbini',
      district: 'Rupandehi',
      municipality: 'Butwal Sub-Metropolitan City',
      address: 'Milanchowk, Butwal',
      universityId: tu.id,
      website: 'https://bmc.edu.np',
      contactEmail: 'info@bmc.edu.np',
      contactPhone: '+977-71-540123',
      eligibility: '+2 or equivalent',
      requiredDocs:
        'Citizenship, +2 transcript & character certificate, passport photos',
      courses: [
        {
          slug: 'bed',
          name: 'Bachelor of Education',
          category: CourseCategory.EDUCATION,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '4 Years',
          durationMonths: 48,
          seatsAvailable: 80,
          tuitionFee: 150000,
          admissionFee: 8000,
          totalFee: 158000,
        },
        {
          slug: 'bsc-general',
          name: 'Bachelor of Science (General)',
          category: CourseCategory.SCIENCE,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '4 Years',
          durationMonths: 48,
          seatsAvailable: 60,
          tuitionFee: 180000,
          admissionFee: 8000,
          totalFee: 188000,
        },
      ],
    },
    {
      slug: 'nepal-law-campus',
      name: 'Nepal Law Campus',
      description:
        'Constituent law campus affiliated with Tribhuvan University, offering undergraduate and graduate law degrees.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Exhibition Road, Kathmandu',
      universityId: tu.id,
      website: 'https://nepallawcampus.edu.np',
      contactEmail: 'info@nepallawcampus.edu.np',
      contactPhone: '+977-1-4258025',
      eligibility: 'Bachelor degree in any discipline for LLB',
      requiredDocs:
        'Citizenship, bachelor transcript & character certificate, passport photos',
      courses: [
        {
          slug: 'bl-llb',
          name: 'Bachelor of Laws (LLB)',
          category: CourseCategory.LAW,
          degreeLevel: DegreeLevel.BACHELOR,
          duration: '3 Years',
          durationMonths: 36,
          seatsAvailable: 100,
          tuitionFee: 120000,
          admissionFee: 6000,
          totalFee: 126000,
        },
      ],
    },

    // ─── Short-course / vocational training institutes ───────────────────────
    // Private IT bootcamps, digital-marketing academies, and vocational
    // training centers — a different segment from the degree colleges above
    // (no university affiliation, shorter certificate-length programs).
    // Fee/duration/seat figures are illustrative estimates (not sourced),
    // same convention as the rest of this seed file; duration values are
    // drawn from the frontend apply form's fixed vocabulary.
    {
      slug: 'broadway-infosys',
      name: 'Broadway Infosys',
      description:
        "One of Nepal's largest and most established IT training institutes, offering hands-on courses in software development, design, and networking with strong placement support.",
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Putalisadak, Kathmandu',
      eligibility:
        'Basic computer literacy; no formal degree required for most courses',
      courses: [
        {
          slug: 'full-stack-development',
          name: 'Full Stack Web Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 65000,
          totalFee: 65000,
        },
        {
          slug: 'python-programming',
          name: 'Python Programming',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 35000,
          totalFee: 35000,
        },
        {
          slug: 'digital-marketing',
          name: 'Digital Marketing',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 30000,
          totalFee: 30000,
        },
      ],
    },
    {
      slug: 'skill-shikshya',
      name: 'Skill Shikshya',
      description:
        'IT training institute in Kathmandu focused on job-ready web development, programming, and digital marketing courses.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kumaripati, Lalitpur',
      website: 'https://skillshikshya.com',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'mern-stack-development',
          name: 'MERN Stack Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 60000,
          totalFee: 60000,
        },
        {
          slug: 'python-programming',
          name: 'Python Programming',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 32000,
          totalFee: 32000,
        },
        {
          slug: 'digital-marketing',
          name: 'Digital Marketing',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 28000,
          totalFee: 28000,
        },
      ],
    },
    {
      slug: 'techaxis',
      name: 'TechAxis',
      description:
        'IT training institute specializing in data science, AI, and cloud/DevOps career tracks for working professionals and graduates.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'New Baneshwor, Kathmandu',
      eligibility:
        'Basic computer literacy; programming background recommended for AI/Data Science tracks',
      courses: [
        {
          slug: 'data-science-ai',
          name: 'Data Science & AI',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 70000,
          totalFee: 70000,
        },
        {
          slug: 'cloud-devops',
          name: 'Cloud Computing & DevOps',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 60000,
          totalFee: 60000,
        },
        {
          slug: 'mern-stack-development',
          name: 'MERN Stack Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 58000,
          totalFee: 58000,
        },
      ],
    },
    {
      slug: 'letslearn',
      name: 'LetsLearn',
      description:
        'Computer and IT training institute offering practical, project-based courses in programming, mobile development, and data analytics.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Tinkune, Kathmandu',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'python-django',
          name: 'Python & Django',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 40000,
          totalFee: 40000,
        },
        {
          slug: 'flutter-app-development',
          name: 'Flutter App Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 45000,
          totalFee: 45000,
        },
        {
          slug: 'data-analytics',
          name: 'Data Analytics',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 42000,
          totalFee: 42000,
        },
      ],
    },
    {
      slug: 'it-training-nepal',
      name: 'IT Training Nepal',
      description:
        'IT training center offering courses across programming languages, web frameworks, and networking/cybersecurity fundamentals.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Putalisadak, Kathmandu',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'java-programming',
          name: 'Java Programming',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 38000,
          totalFee: 38000,
        },
        {
          slug: 'react-js-development',
          name: 'React JS Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 40000,
          totalFee: 40000,
        },
        {
          slug: 'networking-cybersecurity',
          name: 'Networking & Cybersecurity',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 45000,
          totalFee: 45000,
        },
      ],
    },
    {
      slug: 'evolve-it-hub',
      name: 'Evolve IT Hub',
      description:
        'IT training institute offering full stack development, mobile app development, and design courses for career switchers and graduates.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kumaripati, Lalitpur',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'full-stack-development',
          name: 'Full Stack Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 62000,
          totalFee: 62000,
        },
        {
          slug: 'flutter-app-development',
          name: 'Flutter App Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 45000,
          totalFee: 45000,
        },
        {
          slug: 'ui-ux-design',
          name: 'UI/UX Design',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 40000,
          totalFee: 40000,
        },
      ],
    },
    {
      slug: 'digital-gurkha',
      name: 'Digital Gurkha',
      description:
        'Digital marketing academy specializing in SEO, social media, and content marketing training for aspiring marketers and business owners.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Baneshwor, Kathmandu',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'digital-marketing-fundamentals',
          name: 'Digital Marketing Fundamentals',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 25000,
          totalFee: 25000,
        },
        {
          slug: 'seo-content-marketing',
          name: 'SEO & Content Marketing',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 22000,
          totalFee: 22000,
        },
      ],
    },
    {
      slug: 'kathmandu-digital-marketing-institute',
      name: 'Kathmandu Digital Marketing Institute',
      description:
        'Specialized institute offering practical digital marketing training including SEO and paid advertising on Google and Meta platforms.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Putalisadak, Kathmandu',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'digital-marketing-fundamentals',
          name: 'Digital Marketing Fundamentals',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 26000,
          totalFee: 26000,
        },
        {
          slug: 'google-meta-ads-mastery',
          name: 'Google & Meta Ads Mastery',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 24000,
          totalFee: 24000,
        },
      ],
    },
    {
      slug: 'iide-nepal',
      name: 'IIDE - Digital Marketing Course in Nepal',
      description:
        'Digital marketing training provider covering SEO, performance marketing (PPC), email marketing, and content strategy.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'digital-marketing-certification',
          name: 'Digital Marketing Certification',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 32000,
          totalFee: 32000,
        },
        {
          slug: 'performance-marketing',
          name: 'Performance Marketing (PPC & Email)',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 28000,
          totalFee: 28000,
        },
      ],
    },
    {
      slug: 'upskills-nepal',
      name: 'UpSkills Nepal',
      description:
        'Professional skills and IT training institute offering courses spanning digital marketing, data science, cybersecurity, and HR.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      website: 'https://upskillsnepal.com',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'digital-marketing',
          name: 'Digital Marketing',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 27000,
          totalFee: 27000,
        },
        {
          slug: 'data-science-analytics',
          name: 'Data Science & Analytics',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 65000,
          totalFee: 65000,
        },
        {
          slug: 'cybersecurity-fundamentals',
          name: 'Cybersecurity Fundamentals',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 48000,
          totalFee: 48000,
        },
      ],
    },
    {
      slug: 'agile-institute-nepal',
      name: 'Agile Institute Nepal',
      description:
        'Computer training institute and IT learning center offering software development, AI/ML, and cloud/DevOps career tracks.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      website: 'https://agileinstitute.com.np',
      eligibility:
        'Basic computer literacy; programming background recommended for AI/ML track',
      courses: [
        {
          slug: 'software-development',
          name: 'Software Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 55000,
          totalFee: 55000,
        },
        {
          slug: 'ai-machine-learning',
          name: 'AI & Machine Learning',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 72000,
          totalFee: 72000,
        },
        {
          slug: 'cloud-devops',
          name: 'Cloud Computing & DevOps',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 60000,
          totalFee: 60000,
        },
      ],
    },
    {
      slug: 'skillspark',
      name: 'Skillspark',
      description:
        'IT training institute in Kathmandu offering web engineering, cybersecurity/CCNA, and digital marketing courses.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      website: 'https://www.skillspark.com.np',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'web-engineering',
          name: 'Web Engineering',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 55000,
          totalFee: 55000,
        },
        {
          slug: 'cybersecurity-ccna',
          name: 'Cybersecurity & CCNA',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 48000,
          totalFee: 48000,
        },
        {
          slug: 'digital-marketing',
          name: 'Digital Marketing',
          category: CourseCategory.MANAGEMENT,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 26000,
          totalFee: 26000,
        },
      ],
    },
    {
      slug: 'sparkup-it-academy',
      name: 'Sparkup IT Academy',
      description:
        'IT academy offering React JS and web development training with internship placement support for graduates.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      eligibility: 'Basic computer literacy; no formal degree required',
      courses: [
        {
          slug: 'react-js-development',
          name: 'React JS Development',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 42000,
          totalFee: 42000,
        },
        {
          slug: 'web-development-internship',
          name: 'Web Development with Internship',
          category: CourseCategory.IT_COMPUTER_SCIENCE,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 20,
          tuitionFee: 38000,
          totalFee: 38000,
        },
      ],
    },
    {
      slug: 'kathmandu-technical-school',
      name: 'Kathmandu Technical School',
      description:
        'Vocational and technical training school offering hands-on trade courses in electrical, plumbing, HVAC, and auto mechanics.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      eligibility: 'Basic literacy; no formal degree required',
      courses: [
        {
          slug: 'electrical-wiring-maintenance',
          name: 'Electrical Wiring & Maintenance',
          category: CourseCategory.OTHER,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '1 Year',
          durationMonths: 12,
          seatsAvailable: 25,
          tuitionFee: 35000,
          totalFee: 35000,
        },
        {
          slug: 'plumbing-hvac-systems',
          name: 'Plumbing & HVAC Systems',
          category: CourseCategory.OTHER,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '1 Year',
          durationMonths: 12,
          seatsAvailable: 25,
          tuitionFee: 32000,
          totalFee: 32000,
        },
        {
          slug: 'auto-mechanics',
          name: 'Auto Mechanics',
          category: CourseCategory.OTHER,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '1 Year',
          durationMonths: 12,
          seatsAvailable: 25,
          tuitionFee: 38000,
          totalFee: 38000,
        },
      ],
    },
    {
      slug: 'central-college-vocational-training',
      name: 'Central College of Vocational Training Pvt. Ltd.',
      description:
        'Vocational training college offering hospitality and caregiving programs aimed at domestic and overseas employment readiness.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      eligibility: 'Basic literacy; no formal degree required',
      courses: [
        {
          slug: 'hospitality-management',
          name: 'Hospitality Management',
          category: CourseCategory.HOSPITALITY_TOURISM,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '1 Year',
          durationMonths: 12,
          seatsAvailable: 30,
          tuitionFee: 40000,
          totalFee: 40000,
        },
        {
          slug: 'professional-caregiving',
          name: 'Professional Caregiving',
          category: CourseCategory.OTHER,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 30,
          tuitionFee: 30000,
          totalFee: 30000,
        },
      ],
    },
    {
      slug: 'nitvt',
      name: 'Nepal Institute of Technical & Vocational Training Pvt. Ltd. (NITVT)',
      description:
        'Technical and vocational training institute offering industrial and trade-focused certificate programs.',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Kathmandu Metropolitan City',
      eligibility: 'Basic literacy; no formal degree required',
      courses: [
        {
          slug: 'industrial-electrical-technology',
          name: 'Industrial Electrical Technology',
          category: CourseCategory.OTHER,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '1 Year',
          durationMonths: 12,
          seatsAvailable: 25,
          tuitionFee: 40000,
          totalFee: 40000,
        },
        {
          slug: 'technical-vocational-skills-certificate',
          name: 'Technical & Vocational Skills Certificate',
          category: CourseCategory.OTHER,
          degreeLevel: DegreeLevel.CERTIFICATE,
          duration: '6 Months',
          durationMonths: 6,
          seatsAvailable: 25,
          tuitionFee: 28000,
          totalFee: 28000,
        },
      ],
    },
  ];

  for (const collegeData of colleges) {
    const { courses, ...collegeFields } = collegeData;
    const college = await prisma.college.upsert({
      where: { slug: collegeData.slug },
      update: collegeFields,
      create: collegeFields,
    });

    for (const course of courses) {
      await prisma.course.upsert({
        where: { collegeId_slug: { collegeId: college.id, slug: course.slug } },
        update: { ...course, collegeId: college.id },
        create: { ...course, collegeId: college.id },
      });
    }
  }
}
